export const JWT_EXPIRATION_KEY = "JWT_EXPIRATION";
export const JWT_ACCESS_TOKEN_KEY = "JWT_ACCESS_TOKEN_KEY";
export const JWT_REFRESH_TOKEN_KEY = "JWT_REFRESH_TOKEN_KEY";
export const JWT_PHOTO_URL_KEY = "JWT_PHOTO_URL_KEY";
export const APP_USER_ROLE_KEY = "APP_USER_ROLE";
